[tool.poetry]
name = "telegrambot"
version = "0.1.0"
description = ""
authors = ["Safy <safyishanov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytelegrambotapi = "^4.14.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
